version: '3'

services:
  postgres:
    image: "postgres:latest"
    container_name: localdocker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "postgres"
    volumes:
      - "../src/main/resources/init.db:/docker-entrypoint-initdb.d"